# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
# Setup
title:               The Well Tempered Blog
tagline:             'What''s on my mind...'
description:         'A blog about my favourite subjects'
url:                 http://welltemperedbog.com
baseurl:             ''
imgurl:              https://dl.dropboxusercontent.com/u/64397473/blogphotos/
paginate:            3

# Server
port: 4002

# About/contact
author:

# Custom vars
version:             1.0.0
